// Extract Tanzania from world-atlas (50m) and emit an SVG path + projection constants.
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
const topo = JSON.parse(readFileSync(new URL("../node_modules/world-atlas/countries-50m.json", import.meta.url)));
const countries = feature(topo, topo.objects.countries);
const tz = countries.features.find((f) => f.id === "834");
if (!tz) throw new Error("Tanzania not found");
// bounds
let minX = 180, maxX = -180, minY = 90, maxY = -90;
const polys = tz.geometry.type === "Polygon" ? [tz.geometry.coordinates] : tz.geometry.coordinates;
for (const poly of polys) for (const ring of poly) for (const [x, y] of ring) { minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y); }
// equirectangular with latitude correction at ~-6°
const cosLat = Math.cos((-6 * Math.PI) / 180);
const W = 600; const pad = 12;
const spanX = (maxX - minX) * cosLat, spanY = maxY - minY;
const scale = (W - 2 * pad) / spanX;
const H = Math.round(spanY * scale + 2 * pad);
const px = (lon) => pad + (lon - minX) * cosLat * scale;
const py = (lat) => pad + (maxY - lat) * scale;
let d = "";
for (const poly of polys) for (const ring of poly) {
  ring.forEach(([x, y], i) => { d += (i ? "L" : "M") + px(x).toFixed(1) + " " + py(y).toFixed(1); });
  d += "Z";
}
const out = `// Generated by scripts/make-map.mjs from world-atlas countries-50m (Natural Earth, public domain).
export const TZ_VIEWBOX = "0 0 ${W} ${H}";
export const TZ_PATH = ${JSON.stringify(d)};
const MINX = ${minX}, MAXY = ${maxY}, COS = ${cosLat}, SCALE = ${scale}, PAD = ${pad};
export function project(lon: number, lat: number): [number, number] {
  return [PAD + (lon - MINX) * COS * SCALE, PAD + (MAXY - lat) * SCALE];
}
`;
writeFileSync(new URL("../src/components/tanzania-path.ts", import.meta.url), out);
console.log("bounds", minX, maxX, minY, maxY, "size", W, H, "path chars", d.length);
